export const insurerList = [
  {
    id: 1,
    providerName: 'AIA',
    providerNameLowerCases: 'aia',
    username: '',
    password: '',
    isConnected: false,
    isSyncing: false,
    message: '',
    name: '',
    showMessage: false,
    isActive: true,
  },
  {
    id: 3,
    providerName: 'Fidelity',
    providerNameLowerCases: 'fidelity',
    username: '',
    password: '',
    isConnected: false,
    isSyncing: false,
    message: '',
    name: '',
    showMessage: false,
    isActive: true,
  },
  {
    id: 4,
    providerName: 'Asteron Life',
    providerNameLowerCases: 'asteron_life',
    username: '',
    password: '',
    isConnected: false,
    isSyncing: false,
    message: '',
    name: '',
    showMessage: false,
    isActive: true,
  },
  {
    id: 5,
    providerName: 'NIB',
    providerNameLowerCases: 'nib',
    username: '',
    password: '',
    isConnected: false,
    isSyncing: false,
    message: '',
    name: '',
    showMessage: false,
    isActive: false,
  },
  {
    id: 6,
    providerName: 'Partners Life',
    providerNameLowerCases: 'partners_life',
    username: '',
    password: '',
    isConnected: false,
    isSyncing: false,
    message: '',
    name: '',
    showMessage: false,
    isActive: true,
  },
  {
    id: 8,
    providerName: 'AMP',
    providerNameLowerCases: 'amp',
    username: '',
    password: '',
    isConnected: false,
    isSyncing: false,
    message: '',
    name: '',
    showMessage: false,
    isActive: false,
  },
  {
    id: 9,
    providerName: 'Cigna',
    providerNameLowerCases: 'cigna',
    username: '',
    password: '',
    isConnected: false,
    isSyncing: false,
    message: '',
    name: '',
    showMessage: false,
    isActive: true,
  },
  {
    id: 10,
    providerName: 'Southern Cross',
    providerNameLowerCases: 'southern_cross',
    username: '',
    password: '',
    isConnected: false,
    isSyncing: false,
    message: '',
    name: '',
    showMessage: false,
    isActive: false,
  },
  {
    id: 11,
    providerName: 'Accuro',
    providerNameLowerCases: 'accuro',
    username: '',
    password: '',
    isConnected: false,
    isSyncing: false,
    message: '',
    name: '',
    showMessage: false,
    isActive: false,
  },
  {
    id: 12,
    providerName: 'Sovereign',
    providerNameLowerCases: 'sovereign',
    username: '',
    password: '',
    isConnected: false,
    isSyncing: false,
    message: '',
    name: '',
    showMessage: false,
    isActive: true,
  },
];
